"""added settings fields to user

Revision ID: 48ae3c6b70c2
Revises: 
Create Date: 2026-04-20 12:14:56.433900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ae3c6b70c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('budget_exceeded_alert', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('near_limit_alert', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('near_limit_alert')
        batch_op.drop_column('budget_exceeded_alert')
        batch_op.drop_column('email_alerts')
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
