"""add kyc_url to account

Revision ID: 9d5754dbe040
Revises: adcc4b27a636
Create Date: 2026-04-27 12:24:01.539752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5754dbe040'
down_revision = 'adcc4b27a636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('kyc_url')

    # ### end Alembic commands ###
