"""add kyc status

Revision ID: adcc4b27a636
Revises: c1bd92d8ac10
Create Date: 2026-04-27 12:00:01.130466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcc4b27a636'
down_revision = 'c1bd92d8ac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('kyc_status')

    # ### end Alembic commands ###
