"""added goal_id to transaction

Revision ID: c1bd92d8ac10
Revises: 48ae3c6b70c2
Create Date: 2026-04-22 12:34:14.038132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bd92d8ac10'
down_revision = '48ae3c6b70c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
